/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAnalytics {
  'proSubscribers' : bigint,
  'totalViews' : bigint,
  'totalEpisodes' : bigint,
  'totalShows' : bigint,
  'premiumSubscribers' : bigint,
  'totalUsers' : bigint,
  'freeSubscribers' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Category = { 'Drama' : null } |
  { 'Exclusive' : null } |
  { 'RealityTV' : null } |
  { 'Comedy' : null };
export type CommentId = bigint;
export interface CommentPublic {
  'id' : CommentId,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : string,
  'episodeId' : EpisodeId,
}
export interface CreateEpisodeInput {
  'title' : string,
  'thumbnailUrl' : [] | [string],
  'showId' : ShowId,
  'description' : string,
  'seasonId' : SeasonId,
  'episodeNumber' : bigint,
  'durationSeconds' : bigint,
  'videoUrl' : [] | [string],
}
export interface CreateSeasonInput {
  'title' : string,
  'showId' : ShowId,
  'seasonNumber' : bigint,
}
export interface CreateShowInput {
  'coverImageUrl' : [] | [string],
  'title' : string,
  'trailerBlob' : [] | [ExternalBlob],
  'description' : string,
  'isFree' : boolean,
  'category' : Category,
}
export type EpisodeId = bigint;
export interface EpisodePublic {
  'id' : EpisodeId,
  'title' : string,
  'thumbnailUrl' : [] | [string],
  'showId' : ShowId,
  'views' : bigint,
  'createdAt' : Timestamp,
  'description' : string,
  'seasonId' : SeasonId,
  'likes' : bigint,
  'episodeNumber' : bigint,
  'durationSeconds' : bigint,
  'videoUrl' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface PendingSubscriptionPublic {
  'username' : string,
  'userPrincipal' : UserId,
  'planName' : string,
  'requestedAt' : Timestamp,
}
export type SeasonId = bigint;
export interface SeasonPublic {
  'id' : SeasonId,
  'title' : string,
  'showId' : ShowId,
  'episodeCount' : bigint,
  'createdAt' : Timestamp,
  'seasonNumber' : bigint,
}
export type ShowId = bigint;
export interface ShowPublic {
  'id' : ShowId,
  'coverImageUrl' : [] | [string],
  'isApproved' : boolean,
  'title' : string,
  'totalViews' : bigint,
  'seasonCount' : bigint,
  'createdAt' : Timestamp,
  'creatorId' : UserId,
  'description' : string,
  'isFree' : boolean,
  'trailerUrl' : [] | [string],
  'totalLikes' : bigint,
  'isFeatured' : boolean,
  'category' : Category,
}
export interface SignupHistoryEntry {
  'principal' : string,
  'username' : string,
  'currentTier' : string,
  'signedUpAt' : Timestamp,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SubscriptionPlanConfig {
  'priceCredits' : bigint,
  'features' : Array<string>,
  'planId' : string,
  'name' : string,
  'discountPercent' : bigint,
  'discountActive' : boolean,
}
export type SubscriptionTier = { 'Pro' : null } |
  { 'Premium' : null } |
  { 'Free' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateEpisodeInput {
  'title' : [] | [string],
  'thumbnailUrl' : [] | [string],
  'description' : [] | [string],
  'episodeNumber' : [] | [bigint],
  'durationSeconds' : [] | [bigint],
  'videoUrl' : [] | [string],
}
export interface UpdateProfileInput {
  'bio' : string,
  'username' : string,
  'profilePicBlob' : [] | [ExternalBlob],
}
export interface UpdateSeasonInput {
  'title' : [] | [string],
  'seasonNumber' : [] | [bigint],
}
export interface UpdateShowInput {
  'id' : ShowId,
  'coverImageUrl' : [] | [string],
  'title' : string,
  'trailerBlob' : [] | [ExternalBlob],
  'description' : string,
  'isFree' : boolean,
  'category' : Category,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'bio' : string,
  'profilePicUrl' : [] | [string],
  'principal' : UserId,
  'username' : string,
  'createdAt' : Timestamp,
  'subscriptionTier' : SubscriptionTier,
  'subscriptionExpiresAt' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WatchHistoryEntryPublic {
  'showId' : ShowId,
  'lastWatchedAt' : Timestamp,
  'progressSeconds' : bigint,
  'episodeId' : EpisodeId,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'activateSubscription' : ActorMethod<[SubscriptionTier], undefined>,
  'addComment' : ActorMethod<[EpisodeId, string], CommentId>,
  'addToWatchlist' : ActorMethod<[ShowId], undefined>,
  'adminApproveShow' : ActorMethod<[ShowId, boolean], undefined>,
  'adminApproveSubscription' : ActorMethod<[Principal, boolean], undefined>,
  'adminDeleteEpisode' : ActorMethod<[EpisodeId], undefined>,
  'adminGetAnalytics' : ActorMethod<[], AdminAnalytics>,
  'adminGetSignupHistory' : ActorMethod<[], Array<SignupHistoryEntry>>,
  'adminListPendingSubscriptions' : ActorMethod<
    [],
    Array<PendingSubscriptionPublic>
  >,
  'adminListShows' : ActorMethod<[], Array<ShowPublic>>,
  'adminListUsers' : ActorMethod<[], Array<UserProfilePublic>>,
  'adminRemoveSubscription' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminResetAnalytics' : ActorMethod<[], boolean>,
  'adminSetFeatured' : ActorMethod<[ShowId, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [SubscriptionTier, string, string],
    string
  >,
  'createEpisode' : ActorMethod<[CreateEpisodeInput], EpisodeId>,
  'createSeason' : ActorMethod<[CreateSeasonInput], SeasonId>,
  'createShow' : ActorMethod<[CreateShowInput], ShowId>,
  'deleteComment' : ActorMethod<[CommentId], undefined>,
  'deleteEpisode' : ActorMethod<[EpisodeId], undefined>,
  'deleteShow' : ActorMethod<[ShowId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContinueWatching' : ActorMethod<[], Array<EpisodePublic>>,
  'getEpisode' : ActorMethod<[EpisodeId], [] | [EpisodePublic]>,
  'getImvuRecipient' : ActorMethod<[], string>,
  'getShow' : ActorMethod<[ShowId], [] | [ShowPublic]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlanConfig>>,
  'getSubscriptionTier' : ActorMethod<[], SubscriptionTier>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfilePublic]>,
  'getWatchHistory' : ActorMethod<[], Array<WatchHistoryEntryPublic>>,
  'getWatchlist' : ActorMethod<[], Array<ShowPublic>>,
  'hasLikedEpisode' : ActorMethod<[EpisodeId], boolean>,
  'hasLikedShow' : ActorMethod<[ShowId], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'likeEpisode' : ActorMethod<[EpisodeId], undefined>,
  'likeShow' : ActorMethod<[ShowId], undefined>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listApprovedShows' : ActorMethod<[], Array<ShowPublic>>,
  'listComments' : ActorMethod<[EpisodeId], Array<CommentPublic>>,
  'listEpisodes' : ActorMethod<[SeasonId], Array<EpisodePublic>>,
  'listFeaturedShows' : ActorMethod<[], Array<ShowPublic>>,
  'listSeasons' : ActorMethod<[ShowId], Array<SeasonPublic>>,
  'listShowsByCategory' : ActorMethod<[Category], Array<ShowPublic>>,
  'listTrendingShows' : ActorMethod<[], Array<ShowPublic>>,
  'recordView' : ActorMethod<[EpisodeId], undefined>,
  'registerUser' : ActorMethod<[], UserProfilePublic>,
  'removeFromWatchlist' : ActorMethod<[ShowId], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UpdateProfileInput], undefined>,
  'saveImvuRecipient' : ActorMethod<[string], boolean>,
  'saveSubscriptionPlan' : ActorMethod<
    [string, string, bigint, Array<string>, bigint, boolean],
    boolean
  >,
  'searchShows' : ActorMethod<[string], Array<ShowPublic>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unlikeEpisode' : ActorMethod<[EpisodeId], undefined>,
  'unlikeShow' : ActorMethod<[ShowId], undefined>,
  'updateEpisode' : ActorMethod<
    [EpisodeId, UpdateEpisodeInput],
    { 'ok' : EpisodePublic } |
      { 'err' : string }
  >,
  'updateSeason' : ActorMethod<
    [SeasonId, UpdateSeasonInput],
    { 'ok' : SeasonPublic } |
      { 'err' : string }
  >,
  'updateShow' : ActorMethod<[UpdateShowInput], undefined>,
  'updateWatchProgress' : ActorMethod<[EpisodeId, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];