/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SubscriptionTier = IDL.Variant({
  'Pro' : IDL.Null,
  'Premium' : IDL.Null,
  'Free' : IDL.Null,
});
export const EpisodeId = IDL.Nat;
export const CommentId = IDL.Nat;
export const ShowId = IDL.Nat;
export const AdminAnalytics = IDL.Record({
  'proSubscribers' : IDL.Nat,
  'totalViews' : IDL.Nat,
  'totalEpisodes' : IDL.Nat,
  'totalShows' : IDL.Nat,
  'premiumSubscribers' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'freeSubscribers' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const SignupHistoryEntry = IDL.Record({
  'principal' : IDL.Text,
  'username' : IDL.Text,
  'currentTier' : IDL.Text,
  'signedUpAt' : Timestamp,
});
export const UserId = IDL.Principal;
export const PendingSubscriptionPublic = IDL.Record({
  'username' : IDL.Text,
  'userPrincipal' : UserId,
  'planName' : IDL.Text,
  'requestedAt' : Timestamp,
});
export const Category = IDL.Variant({
  'Drama' : IDL.Null,
  'Exclusive' : IDL.Null,
  'RealityTV' : IDL.Null,
  'Comedy' : IDL.Null,
});
export const ShowPublic = IDL.Record({
  'id' : ShowId,
  'coverImageUrl' : IDL.Opt(IDL.Text),
  'isApproved' : IDL.Bool,
  'title' : IDL.Text,
  'totalViews' : IDL.Nat,
  'seasonCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'creatorId' : UserId,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'trailerUrl' : IDL.Opt(IDL.Text),
  'totalLikes' : IDL.Nat,
  'isFeatured' : IDL.Bool,
  'category' : Category,
});
export const UserProfilePublic = IDL.Record({
  'bio' : IDL.Text,
  'profilePicUrl' : IDL.Opt(IDL.Text),
  'principal' : UserId,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'subscriptionTier' : SubscriptionTier,
  'subscriptionExpiresAt' : IDL.Opt(IDL.Int),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SeasonId = IDL.Nat;
export const CreateEpisodeInput = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'showId' : ShowId,
  'description' : IDL.Text,
  'seasonId' : SeasonId,
  'episodeNumber' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const CreateSeasonInput = IDL.Record({
  'title' : IDL.Text,
  'showId' : ShowId,
  'seasonNumber' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateShowInput = IDL.Record({
  'coverImageUrl' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'trailerBlob' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'category' : Category,
});
export const EpisodePublic = IDL.Record({
  'id' : EpisodeId,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'showId' : ShowId,
  'views' : IDL.Nat,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'seasonId' : SeasonId,
  'likes' : IDL.Nat,
  'episodeNumber' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SubscriptionPlanConfig = IDL.Record({
  'priceCredits' : IDL.Nat,
  'features' : IDL.Vec(IDL.Text),
  'planId' : IDL.Text,
  'name' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'discountActive' : IDL.Bool,
});
export const WatchHistoryEntryPublic = IDL.Record({
  'showId' : ShowId,
  'lastWatchedAt' : Timestamp,
  'progressSeconds' : IDL.Nat,
  'episodeId' : EpisodeId,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const CommentPublic = IDL.Record({
  'id' : CommentId,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'episodeId' : EpisodeId,
});
export const SeasonPublic = IDL.Record({
  'id' : SeasonId,
  'title' : IDL.Text,
  'showId' : ShowId,
  'episodeCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'seasonNumber' : IDL.Nat,
});
export const UpdateProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'profilePicBlob' : IDL.Opt(ExternalBlob),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateEpisodeInput = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'episodeNumber' : IDL.Opt(IDL.Nat),
  'durationSeconds' : IDL.Opt(IDL.Nat),
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const UpdateSeasonInput = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'seasonNumber' : IDL.Opt(IDL.Nat),
});
export const UpdateShowInput = IDL.Record({
  'id' : ShowId,
  'coverImageUrl' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'trailerBlob' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'category' : Category,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'activateSubscription' : IDL.Func([SubscriptionTier], [], []),
  'addComment' : IDL.Func([EpisodeId, IDL.Text], [CommentId], []),
  'addToWatchlist' : IDL.Func([ShowId], [], []),
  'adminApproveShow' : IDL.Func([ShowId, IDL.Bool], [], []),
  'adminApproveSubscription' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'adminDeleteEpisode' : IDL.Func([EpisodeId], [], []),
  'adminGetAnalytics' : IDL.Func([], [AdminAnalytics], ['query']),
  'adminGetSignupHistory' : IDL.Func(
      [],
      [IDL.Vec(SignupHistoryEntry)],
      ['query'],
    ),
  'adminListPendingSubscriptions' : IDL.Func(
      [],
      [IDL.Vec(PendingSubscriptionPublic)],
      ['query'],
    ),
  'adminListShows' : IDL.Func([], [IDL.Vec(ShowPublic)], ['query']),
  'adminListUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
  'adminRemoveSubscription' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminResetAnalytics' : IDL.Func([], [IDL.Bool], []),
  'adminSetFeatured' : IDL.Func([ShowId, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [SubscriptionTier, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createEpisode' : IDL.Func([CreateEpisodeInput], [EpisodeId], []),
  'createSeason' : IDL.Func([CreateSeasonInput], [SeasonId], []),
  'createShow' : IDL.Func([CreateShowInput], [ShowId], []),
  'deleteComment' : IDL.Func([CommentId], [], []),
  'deleteEpisode' : IDL.Func([EpisodeId], [], []),
  'deleteShow' : IDL.Func([ShowId], [], []),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContinueWatching' : IDL.Func([], [IDL.Vec(EpisodePublic)], ['query']),
  'getEpisode' : IDL.Func([EpisodeId], [IDL.Opt(EpisodePublic)], ['query']),
  'getImvuRecipient' : IDL.Func([], [IDL.Text], ['query']),
  'getShow' : IDL.Func([ShowId], [IDL.Opt(ShowPublic)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubscriptionPlans' : IDL.Func(
      [],
      [IDL.Vec(SubscriptionPlanConfig)],
      ['query'],
    ),
  'getSubscriptionTier' : IDL.Func([], [SubscriptionTier], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getWatchHistory' : IDL.Func(
      [],
      [IDL.Vec(WatchHistoryEntryPublic)],
      ['query'],
    ),
  'getWatchlist' : IDL.Func([], [IDL.Vec(ShowPublic)], ['query']),
  'hasLikedEpisode' : IDL.Func([EpisodeId], [IDL.Bool], ['query']),
  'hasLikedShow' : IDL.Func([ShowId], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'likeEpisode' : IDL.Func([EpisodeId], [], []),
  'likeShow' : IDL.Func([ShowId], [], []),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listApprovedShows' : IDL.Func([], [IDL.Vec(ShowPublic)], ['query']),
  'listComments' : IDL.Func([EpisodeId], [IDL.Vec(CommentPublic)], ['query']),
  'listEpisodes' : IDL.Func([SeasonId], [IDL.Vec(EpisodePublic)], ['query']),
  'listFeaturedShows' : IDL.Func([], [IDL.Vec(ShowPublic)], ['query']),
  'listSeasons' : IDL.Func([ShowId], [IDL.Vec(SeasonPublic)], ['query']),
  'listShowsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(ShowPublic)],
      ['query'],
    ),
  'listTrendingShows' : IDL.Func([], [IDL.Vec(ShowPublic)], ['query']),
  'recordView' : IDL.Func([EpisodeId], [], []),
  'registerUser' : IDL.Func([], [UserProfilePublic], []),
  'removeFromWatchlist' : IDL.Func([ShowId], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UpdateProfileInput], [], []),
  'saveImvuRecipient' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveSubscriptionPlan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Nat, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'searchShows' : IDL.Func([IDL.Text], [IDL.Vec(ShowPublic)], ['query']),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unlikeEpisode' : IDL.Func([EpisodeId], [], []),
  'unlikeShow' : IDL.Func([ShowId], [], []),
  'updateEpisode' : IDL.Func(
      [EpisodeId, UpdateEpisodeInput],
      [IDL.Variant({ 'ok' : EpisodePublic, 'err' : IDL.Text })],
      [],
    ),
  'updateSeason' : IDL.Func(
      [SeasonId, UpdateSeasonInput],
      [IDL.Variant({ 'ok' : SeasonPublic, 'err' : IDL.Text })],
      [],
    ),
  'updateShow' : IDL.Func([UpdateShowInput], [], []),
  'updateWatchProgress' : IDL.Func([EpisodeId, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SubscriptionTier = IDL.Variant({
    'Pro' : IDL.Null,
    'Premium' : IDL.Null,
    'Free' : IDL.Null,
  });
  const EpisodeId = IDL.Nat;
  const CommentId = IDL.Nat;
  const ShowId = IDL.Nat;
  const AdminAnalytics = IDL.Record({
    'proSubscribers' : IDL.Nat,
    'totalViews' : IDL.Nat,
    'totalEpisodes' : IDL.Nat,
    'totalShows' : IDL.Nat,
    'premiumSubscribers' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'freeSubscribers' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const SignupHistoryEntry = IDL.Record({
    'principal' : IDL.Text,
    'username' : IDL.Text,
    'currentTier' : IDL.Text,
    'signedUpAt' : Timestamp,
  });
  const UserId = IDL.Principal;
  const PendingSubscriptionPublic = IDL.Record({
    'username' : IDL.Text,
    'userPrincipal' : UserId,
    'planName' : IDL.Text,
    'requestedAt' : Timestamp,
  });
  const Category = IDL.Variant({
    'Drama' : IDL.Null,
    'Exclusive' : IDL.Null,
    'RealityTV' : IDL.Null,
    'Comedy' : IDL.Null,
  });
  const ShowPublic = IDL.Record({
    'id' : ShowId,
    'coverImageUrl' : IDL.Opt(IDL.Text),
    'isApproved' : IDL.Bool,
    'title' : IDL.Text,
    'totalViews' : IDL.Nat,
    'seasonCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'creatorId' : UserId,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'trailerUrl' : IDL.Opt(IDL.Text),
    'totalLikes' : IDL.Nat,
    'isFeatured' : IDL.Bool,
    'category' : Category,
  });
  const UserProfilePublic = IDL.Record({
    'bio' : IDL.Text,
    'profilePicUrl' : IDL.Opt(IDL.Text),
    'principal' : UserId,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'subscriptionTier' : SubscriptionTier,
    'subscriptionExpiresAt' : IDL.Opt(IDL.Int),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SeasonId = IDL.Nat;
  const CreateEpisodeInput = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'showId' : ShowId,
    'description' : IDL.Text,
    'seasonId' : SeasonId,
    'episodeNumber' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const CreateSeasonInput = IDL.Record({
    'title' : IDL.Text,
    'showId' : ShowId,
    'seasonNumber' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateShowInput = IDL.Record({
    'coverImageUrl' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'trailerBlob' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'category' : Category,
  });
  const EpisodePublic = IDL.Record({
    'id' : EpisodeId,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'showId' : ShowId,
    'views' : IDL.Nat,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'seasonId' : SeasonId,
    'likes' : IDL.Nat,
    'episodeNumber' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SubscriptionPlanConfig = IDL.Record({
    'priceCredits' : IDL.Nat,
    'features' : IDL.Vec(IDL.Text),
    'planId' : IDL.Text,
    'name' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'discountActive' : IDL.Bool,
  });
  const WatchHistoryEntryPublic = IDL.Record({
    'showId' : ShowId,
    'lastWatchedAt' : Timestamp,
    'progressSeconds' : IDL.Nat,
    'episodeId' : EpisodeId,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const CommentPublic = IDL.Record({
    'id' : CommentId,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'episodeId' : EpisodeId,
  });
  const SeasonPublic = IDL.Record({
    'id' : SeasonId,
    'title' : IDL.Text,
    'showId' : ShowId,
    'episodeCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'seasonNumber' : IDL.Nat,
  });
  const UpdateProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'profilePicBlob' : IDL.Opt(ExternalBlob),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateEpisodeInput = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'episodeNumber' : IDL.Opt(IDL.Nat),
    'durationSeconds' : IDL.Opt(IDL.Nat),
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const UpdateSeasonInput = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'seasonNumber' : IDL.Opt(IDL.Nat),
  });
  const UpdateShowInput = IDL.Record({
    'id' : ShowId,
    'coverImageUrl' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'trailerBlob' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'category' : Category,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'activateSubscription' : IDL.Func([SubscriptionTier], [], []),
    'addComment' : IDL.Func([EpisodeId, IDL.Text], [CommentId], []),
    'addToWatchlist' : IDL.Func([ShowId], [], []),
    'adminApproveShow' : IDL.Func([ShowId, IDL.Bool], [], []),
    'adminApproveSubscription' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'adminDeleteEpisode' : IDL.Func([EpisodeId], [], []),
    'adminGetAnalytics' : IDL.Func([], [AdminAnalytics], ['query']),
    'adminGetSignupHistory' : IDL.Func(
        [],
        [IDL.Vec(SignupHistoryEntry)],
        ['query'],
      ),
    'adminListPendingSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(PendingSubscriptionPublic)],
        ['query'],
      ),
    'adminListShows' : IDL.Func([], [IDL.Vec(ShowPublic)], ['query']),
    'adminListUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
    'adminRemoveSubscription' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminResetAnalytics' : IDL.Func([], [IDL.Bool], []),
    'adminSetFeatured' : IDL.Func([ShowId, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [SubscriptionTier, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createEpisode' : IDL.Func([CreateEpisodeInput], [EpisodeId], []),
    'createSeason' : IDL.Func([CreateSeasonInput], [SeasonId], []),
    'createShow' : IDL.Func([CreateShowInput], [ShowId], []),
    'deleteComment' : IDL.Func([CommentId], [], []),
    'deleteEpisode' : IDL.Func([EpisodeId], [], []),
    'deleteShow' : IDL.Func([ShowId], [], []),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContinueWatching' : IDL.Func([], [IDL.Vec(EpisodePublic)], ['query']),
    'getEpisode' : IDL.Func([EpisodeId], [IDL.Opt(EpisodePublic)], ['query']),
    'getImvuRecipient' : IDL.Func([], [IDL.Text], ['query']),
    'getShow' : IDL.Func([ShowId], [IDL.Opt(ShowPublic)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubscriptionPlans' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionPlanConfig)],
        ['query'],
      ),
    'getSubscriptionTier' : IDL.Func([], [SubscriptionTier], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getWatchHistory' : IDL.Func(
        [],
        [IDL.Vec(WatchHistoryEntryPublic)],
        ['query'],
      ),
    'getWatchlist' : IDL.Func([], [IDL.Vec(ShowPublic)], ['query']),
    'hasLikedEpisode' : IDL.Func([EpisodeId], [IDL.Bool], ['query']),
    'hasLikedShow' : IDL.Func([ShowId], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'likeEpisode' : IDL.Func([EpisodeId], [], []),
    'likeShow' : IDL.Func([ShowId], [], []),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listApprovedShows' : IDL.Func([], [IDL.Vec(ShowPublic)], ['query']),
    'listComments' : IDL.Func([EpisodeId], [IDL.Vec(CommentPublic)], ['query']),
    'listEpisodes' : IDL.Func([SeasonId], [IDL.Vec(EpisodePublic)], ['query']),
    'listFeaturedShows' : IDL.Func([], [IDL.Vec(ShowPublic)], ['query']),
    'listSeasons' : IDL.Func([ShowId], [IDL.Vec(SeasonPublic)], ['query']),
    'listShowsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(ShowPublic)],
        ['query'],
      ),
    'listTrendingShows' : IDL.Func([], [IDL.Vec(ShowPublic)], ['query']),
    'recordView' : IDL.Func([EpisodeId], [], []),
    'registerUser' : IDL.Func([], [UserProfilePublic], []),
    'removeFromWatchlist' : IDL.Func([ShowId], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UpdateProfileInput], [], []),
    'saveImvuRecipient' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveSubscriptionPlan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Nat, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'searchShows' : IDL.Func([IDL.Text], [IDL.Vec(ShowPublic)], ['query']),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unlikeEpisode' : IDL.Func([EpisodeId], [], []),
    'unlikeShow' : IDL.Func([ShowId], [], []),
    'updateEpisode' : IDL.Func(
        [EpisodeId, UpdateEpisodeInput],
        [IDL.Variant({ 'ok' : EpisodePublic, 'err' : IDL.Text })],
        [],
      ),
    'updateSeason' : IDL.Func(
        [SeasonId, UpdateSeasonInput],
        [IDL.Variant({ 'ok' : SeasonPublic, 'err' : IDL.Text })],
        [],
      ),
    'updateShow' : IDL.Func([UpdateShowInput], [], []),
    'updateWatchProgress' : IDL.Func([EpisodeId, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };