/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UpdateEpisodeInput {
    title?: string;
    thumbnailUrl?: string;
    description?: string;
    episodeNumber?: bigint;
    durationSeconds?: bigint;
    videoUrl?: string;
}
export interface AdminAnalytics {
    proSubscribers: bigint;
    totalViews: bigint;
    totalEpisodes: bigint;
    totalShows: bigint;
    premiumSubscribers: bigint;
    totalUsers: bigint;
    freeSubscribers: bigint;
}
export interface EpisodePublic {
    id: EpisodeId;
    title: string;
    thumbnailUrl?: string;
    showId: ShowId;
    views: bigint;
    createdAt: Timestamp;
    description: string;
    seasonId: SeasonId;
    likes: bigint;
    episodeNumber: bigint;
    durationSeconds: bigint;
    videoUrl?: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ShowPublic {
    id: ShowId;
    coverImageUrl?: string;
    isApproved: boolean;
    title: string;
    totalViews: bigint;
    seasonCount: bigint;
    createdAt: Timestamp;
    creatorId: UserId;
    description: string;
    isFree: boolean;
    trailerUrl?: string;
    totalLikes: bigint;
    isFeatured: boolean;
    category: Category;
}
export interface PendingSubscriptionPublic {
    username: string;
    userPrincipal: UserId;
    planName: string;
    requestedAt: Timestamp;
}
export type SeasonId = bigint;
export interface UpdateSeasonInput {
    title?: string;
    seasonNumber?: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface WatchHistoryEntryPublic {
    showId: ShowId;
    lastWatchedAt: Timestamp;
    progressSeconds: bigint;
    episodeId: EpisodeId;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface CreateEpisodeInput {
    title: string;
    thumbnailUrl?: string;
    showId: ShowId;
    description: string;
    seasonId: SeasonId;
    episodeNumber: bigint;
    durationSeconds: bigint;
    videoUrl?: string;
}
export type CommentId = bigint;
export interface SeasonPublic {
    id: SeasonId;
    title: string;
    showId: ShowId;
    episodeCount: bigint;
    createdAt: Timestamp;
    seasonNumber: bigint;
}
export interface CommentPublic {
    id: CommentId;
    authorId: UserId;
    createdAt: Timestamp;
    text: string;
    episodeId: EpisodeId;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UpdateShowInput {
    id: ShowId;
    coverImageUrl?: string;
    title: string;
    trailerBlob?: ExternalBlob;
    description: string;
    isFree: boolean;
    category: Category;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CreateShowInput {
    coverImageUrl?: string;
    title: string;
    trailerBlob?: ExternalBlob;
    description: string;
    isFree: boolean;
    category: Category;
}
export interface SubscriptionPlanConfig {
    priceCredits: bigint;
    features: Array<string>;
    planId: string;
    name: string;
    discountPercent: bigint;
    discountActive: boolean;
}
export interface UserProfilePublic {
    bio: string;
    profilePicUrl?: string;
    principal: UserId;
    username: string;
    createdAt: Timestamp;
    subscriptionTier: SubscriptionTier;
    subscriptionExpiresAt?: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface UpdateProfileInput {
    bio: string;
    username: string;
    profilePicBlob?: ExternalBlob;
}
export interface SignupHistoryEntry {
    principal: string;
    username: string;
    currentTier: string;
    signedUpAt: Timestamp;
}
export type ShowId = bigint;
export interface CreateSeasonInput {
    title: string;
    showId: ShowId;
    seasonNumber: bigint;
}
export type EpisodeId = bigint;
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Category {
    Drama = "Drama",
    Exclusive = "Exclusive",
    RealityTV = "RealityTV",
    Comedy = "Comedy"
}
export enum SubscriptionTier {
    Pro = "Pro",
    Premium = "Premium",
    Free = "Free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    activateSubscription(tier: SubscriptionTier): Promise<void>;
    addComment(episodeId: EpisodeId, text: string): Promise<CommentId>;
    addToWatchlist(showId: ShowId): Promise<void>;
    adminApproveShow(showId: ShowId, approved: boolean): Promise<void>;
    adminApproveSubscription(user: Principal, approve: boolean): Promise<void>;
    adminDeleteEpisode(episodeId: EpisodeId): Promise<void>;
    adminGetAnalytics(): Promise<AdminAnalytics>;
    adminGetSignupHistory(): Promise<Array<SignupHistoryEntry>>;
    adminListPendingSubscriptions(): Promise<Array<PendingSubscriptionPublic>>;
    adminListShows(): Promise<Array<ShowPublic>>;
    adminListUsers(): Promise<Array<UserProfilePublic>>;
    adminRemoveSubscription(user: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminResetAnalytics(): Promise<boolean>;
    adminSetFeatured(showId: ShowId, featured: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(tier: SubscriptionTier, successUrl: string, cancelUrl: string): Promise<string>;
    createEpisode(input: CreateEpisodeInput): Promise<EpisodeId>;
    createSeason(input: CreateSeasonInput): Promise<SeasonId>;
    createShow(input: CreateShowInput): Promise<ShowId>;
    deleteComment(commentId: CommentId): Promise<void>;
    deleteEpisode(episodeId: EpisodeId): Promise<void>;
    deleteShow(showId: ShowId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfilePublic | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContinueWatching(): Promise<Array<EpisodePublic>>;
    getEpisode(episodeId: EpisodeId): Promise<EpisodePublic | null>;
    getImvuRecipient(): Promise<string>;
    getShow(showId: ShowId): Promise<ShowPublic | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSubscriptionPlans(): Promise<Array<SubscriptionPlanConfig>>;
    getSubscriptionTier(): Promise<SubscriptionTier>;
    getUserProfile(user: Principal): Promise<UserProfilePublic | null>;
    getWatchHistory(): Promise<Array<WatchHistoryEntryPublic>>;
    getWatchlist(): Promise<Array<ShowPublic>>;
    hasLikedEpisode(episodeId: EpisodeId): Promise<boolean>;
    hasLikedShow(showId: ShowId): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    likeEpisode(episodeId: EpisodeId): Promise<void>;
    likeShow(showId: ShowId): Promise<void>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listApprovedShows(): Promise<Array<ShowPublic>>;
    listComments(episodeId: EpisodeId): Promise<Array<CommentPublic>>;
    listEpisodes(seasonId: SeasonId): Promise<Array<EpisodePublic>>;
    listFeaturedShows(): Promise<Array<ShowPublic>>;
    listSeasons(showId: ShowId): Promise<Array<SeasonPublic>>;
    listShowsByCategory(category: Category): Promise<Array<ShowPublic>>;
    listTrendingShows(): Promise<Array<ShowPublic>>;
    recordView(episodeId: EpisodeId): Promise<void>;
    registerUser(): Promise<UserProfilePublic>;
    removeFromWatchlist(showId: ShowId): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(input: UpdateProfileInput): Promise<void>;
    saveImvuRecipient(recipient: string): Promise<boolean>;
    saveSubscriptionPlan(planId: string, name: string, priceCredits: bigint, features: Array<string>, discountPercent: bigint, discountActive: boolean): Promise<boolean>;
    searchShows(term: string): Promise<Array<ShowPublic>>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unlikeEpisode(episodeId: EpisodeId): Promise<void>;
    unlikeShow(showId: ShowId): Promise<void>;
    updateEpisode(episodeId: EpisodeId, input: UpdateEpisodeInput): Promise<{
        __kind__: "ok";
        ok: EpisodePublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateSeason(seasonId: SeasonId, input: UpdateSeasonInput): Promise<{
        __kind__: "ok";
        ok: SeasonPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateShow(input: UpdateShowInput): Promise<void>;
    updateWatchProgress(episodeId: EpisodeId, progressSeconds: bigint): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, Category as _Category, CreateEpisodeInput as _CreateEpisodeInput, CreateShowInput as _CreateShowInput, EpisodeId as _EpisodeId, EpisodePublic as _EpisodePublic, ExternalBlob as _ExternalBlob, SeasonId as _SeasonId, SeasonPublic as _SeasonPublic, ShowId as _ShowId, ShowPublic as _ShowPublic, StripeSessionStatus as _StripeSessionStatus, SubscriptionTier as _SubscriptionTier, Timestamp as _Timestamp, UpdateEpisodeInput as _UpdateEpisodeInput, UpdateProfileInput as _UpdateProfileInput, UpdateSeasonInput as _UpdateSeasonInput, UpdateShowInput as _UpdateShowInput, UserApprovalInfo as _UserApprovalInfo, UserId as _UserId, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async activateSubscription(arg0: SubscriptionTier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateSubscription(to_candid_SubscriptionTier_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateSubscription(to_candid_SubscriptionTier_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addComment(arg0: EpisodeId, arg1: string): Promise<CommentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addToWatchlist(arg0: ShowId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0);
            return result;
        }
    }
    async adminApproveShow(arg0: ShowId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveShow(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveShow(arg0, arg1);
            return result;
        }
    }
    async adminApproveSubscription(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveSubscription(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveSubscription(arg0, arg1);
            return result;
        }
    }
    async adminDeleteEpisode(arg0: EpisodeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteEpisode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteEpisode(arg0);
            return result;
        }
    }
    async adminGetAnalytics(): Promise<AdminAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAnalytics();
            return result;
        }
    }
    async adminGetSignupHistory(): Promise<Array<SignupHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetSignupHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetSignupHistory();
            return result;
        }
    }
    async adminListPendingSubscriptions(): Promise<Array<PendingSubscriptionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListPendingSubscriptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListPendingSubscriptions();
            return result;
        }
    }
    async adminListShows(): Promise<Array<ShowPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListShows();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListShows();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListUsers(): Promise<Array<UserProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListUsers();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListUsers();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRemoveSubscription(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveSubscription(arg0);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveSubscription(arg0);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminResetAnalytics(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetAnalytics();
            return result;
        }
    }
    async adminSetFeatured(arg0: ShowId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetFeatured(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetFeatured(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: SubscriptionTier, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(to_candid_SubscriptionTier_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(to_candid_SubscriptionTier_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async createEpisode(arg0: CreateEpisodeInput): Promise<EpisodeId> {
        if (this.processError) {
            try {
                const result = await this.actor.createEpisode(to_candid_CreateEpisodeInput_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEpisode(to_candid_CreateEpisodeInput_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSeason(arg0: CreateSeasonInput): Promise<SeasonId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSeason(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSeason(arg0);
            return result;
        }
    }
    async createShow(arg0: CreateShowInput): Promise<ShowId> {
        if (this.processError) {
            try {
                const result = await this.actor.createShow(await to_candid_CreateShowInput_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShow(await to_candid_CreateShowInput_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteComment(arg0: CommentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteEpisode(arg0: EpisodeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEpisode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEpisode(arg0);
            return result;
        }
    }
    async deleteShow(arg0: ShowId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShow(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContinueWatching(): Promise<Array<EpisodePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContinueWatching();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContinueWatching();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEpisode(arg0: EpisodeId): Promise<EpisodePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEpisode(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEpisode(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImvuRecipient(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getImvuRecipient();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImvuRecipient();
            return result;
        }
    }
    async getShow(arg0: ShowId): Promise<ShowPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShow(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShow(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionPlans(): Promise<Array<SubscriptionPlanConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionPlans();
            return result;
        }
    }
    async getSubscriptionTier(): Promise<SubscriptionTier> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionTier();
                return from_candid_SubscriptionTier_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionTier();
            return from_candid_SubscriptionTier_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWatchHistory(): Promise<Array<WatchHistoryEntryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchHistory();
            return result;
        }
    }
    async getWatchlist(): Promise<Array<ShowPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasLikedEpisode(arg0: EpisodeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasLikedEpisode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasLikedEpisode(arg0);
            return result;
        }
    }
    async hasLikedShow(arg0: ShowId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasLikedShow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasLikedShow(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async likeEpisode(arg0: EpisodeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeEpisode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeEpisode(arg0);
            return result;
        }
    }
    async likeShow(arg0: ShowId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeShow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeShow(arg0);
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApprovedShows(): Promise<Array<ShowPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovedShows();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovedShows();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async listComments(arg0: EpisodeId): Promise<Array<CommentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listComments(arg0);
            return result;
        }
    }
    async listEpisodes(arg0: SeasonId): Promise<Array<EpisodePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEpisodes(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEpisodes(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFeaturedShows(): Promise<Array<ShowPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeaturedShows();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeaturedShows();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSeasons(arg0: ShowId): Promise<Array<SeasonPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSeasons(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSeasons(arg0);
            return result;
        }
    }
    async listShowsByCategory(arg0: Category): Promise<Array<ShowPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listShowsByCategory(to_candid_Category_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listShowsByCategory(to_candid_Category_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTrendingShows(): Promise<Array<ShowPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrendingShows();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrendingShows();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordView(arg0: EpisodeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordView(arg0);
            return result;
        }
    }
    async registerUser(): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser();
                return from_candid_UserProfilePublic_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser();
            return from_candid_UserProfilePublic_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromWatchlist(arg0: ShowId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UpdateProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UpdateProfileInput_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UpdateProfileInput_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveImvuRecipient(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveImvuRecipient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveImvuRecipient(arg0);
            return result;
        }
    }
    async saveSubscriptionPlan(arg0: string, arg1: string, arg2: bigint, arg3: Array<string>, arg4: bigint, arg5: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSubscriptionPlan(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSubscriptionPlan(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async searchShows(arg0: string): Promise<Array<ShowPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchShows(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchShows(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unlikeEpisode(arg0: EpisodeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeEpisode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeEpisode(arg0);
            return result;
        }
    }
    async unlikeShow(arg0: ShowId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeShow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeShow(arg0);
            return result;
        }
    }
    async updateEpisode(arg0: EpisodeId, arg1: UpdateEpisodeInput): Promise<{
        __kind__: "ok";
        ok: EpisodePublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEpisode(arg0, to_candid_UpdateEpisodeInput_n52(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEpisode(arg0, to_candid_UpdateEpisodeInput_n52(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSeason(arg0: SeasonId, arg1: UpdateSeasonInput): Promise<{
        __kind__: "ok";
        ok: SeasonPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSeason(arg0, to_candid_UpdateSeasonInput_n55(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSeason(arg0, to_candid_UpdateSeasonInput_n55(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateShow(arg0: UpdateShowInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShow(await to_candid_UpdateShowInput_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShow(await to_candid_UpdateShowInput_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateWatchProgress(arg0: EpisodeId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWatchProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWatchProgress(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_EpisodePublic_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EpisodePublic): EpisodePublic {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_ShowPublic_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShowPublic): ShowPublic {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EpisodePublic]): EpisodePublic | null {
    return value.length === 0 ? null : from_candid_EpisodePublic_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShowPublic]): ShowPublic | null {
    return value.length === 0 ? null : from_candid_ShowPublic_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ShowId;
    coverImageUrl: [] | [string];
    isApproved: boolean;
    title: string;
    totalViews: bigint;
    seasonCount: bigint;
    createdAt: _Timestamp;
    creatorId: _UserId;
    description: string;
    isFree: boolean;
    trailerUrl: [] | [string];
    totalLikes: bigint;
    isFeatured: boolean;
    category: _Category;
}): {
    id: ShowId;
    coverImageUrl?: string;
    isApproved: boolean;
    title: string;
    totalViews: bigint;
    seasonCount: bigint;
    createdAt: Timestamp;
    creatorId: UserId;
    description: string;
    isFree: boolean;
    trailerUrl?: string;
    totalLikes: bigint;
    isFeatured: boolean;
    category: Category;
} {
    return {
        id: value.id,
        coverImageUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.coverImageUrl)),
        isApproved: value.isApproved,
        title: value.title,
        totalViews: value.totalViews,
        seasonCount: value.seasonCount,
        createdAt: value.createdAt,
        creatorId: value.creatorId,
        description: value.description,
        isFree: value.isFree,
        trailerUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.trailerUrl)),
        totalLikes: value.totalLikes,
        isFeatured: value.isFeatured,
        category: from_candid_Category_n14(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    profilePicUrl: [] | [string];
    principal: _UserId;
    username: string;
    createdAt: _Timestamp;
    subscriptionTier: _SubscriptionTier;
    subscriptionExpiresAt: [] | [bigint];
}): {
    bio: string;
    profilePicUrl?: string;
    principal: UserId;
    username: string;
    createdAt: Timestamp;
    subscriptionTier: SubscriptionTier;
    subscriptionExpiresAt?: bigint;
} {
    return {
        bio: value.bio,
        profilePicUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.profilePicUrl)),
        principal: value.principal,
        username: value.username,
        createdAt: value.createdAt,
        subscriptionTier: from_candid_SubscriptionTier_n19(_uploadFile, _downloadFile, value.subscriptionTier),
        subscriptionExpiresAt: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.subscriptionExpiresAt))
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EpisodeId;
    title: string;
    thumbnailUrl: [] | [string];
    showId: _ShowId;
    views: bigint;
    createdAt: _Timestamp;
    description: string;
    seasonId: _SeasonId;
    likes: bigint;
    episodeNumber: bigint;
    durationSeconds: bigint;
    videoUrl: [] | [string];
}): {
    id: EpisodeId;
    title: string;
    thumbnailUrl?: string;
    showId: ShowId;
    views: bigint;
    createdAt: Timestamp;
    description: string;
    seasonId: SeasonId;
    likes: bigint;
    episodeNumber: bigint;
    durationSeconds: bigint;
    videoUrl?: string;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.thumbnailUrl)),
        showId: value.showId,
        views: value.views,
        createdAt: value.createdAt,
        description: value.description,
        seasonId: value.seasonId,
        likes: value.likes,
        episodeNumber: value.episodeNumber,
        durationSeconds: value.durationSeconds,
        videoUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.videoUrl))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n46(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Drama: null;
} | {
    Exclusive: null;
} | {
    RealityTV: null;
} | {
    Comedy: null;
}): Category {
    return "Drama" in value ? Category.Drama : "Exclusive" in value ? Category.Exclusive : "RealityTV" in value ? Category.RealityTV : "Comedy" in value ? Category.Comedy : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Pro: null;
} | {
    Premium: null;
} | {
    Free: null;
}): SubscriptionTier {
    return "Pro" in value ? SubscriptionTier.Pro : "Premium" in value ? SubscriptionTier.Premium : "Free" in value ? SubscriptionTier.Free : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n42(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _EpisodePublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: EpisodePublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_EpisodePublic_n36(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SeasonPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SeasonPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShowPublic>): Array<ShowPublic> {
    return value.map((x)=>from_candid_ShowPublic_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfilePublic>): Array<UserProfilePublic> {
    return value.map((x)=>from_candid_UserProfilePublic_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EpisodePublic>): Array<EpisodePublic> {
    return value.map((x)=>from_candid_EpisodePublic_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n44(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_CreateEpisodeInput_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateEpisodeInput): _CreateEpisodeInput {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateShowInput_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateShowInput): Promise<_CreateShowInput> {
    return await to_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_SubscriptionTier_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateEpisodeInput_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateEpisodeInput): _UpdateEpisodeInput {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdateProfileInput_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileInput): Promise<_UpdateProfileInput> {
    return await to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateSeasonInput_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateSeasonInput): _UpdateSeasonInput {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdateShowInput_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateShowInput): Promise<_UpdateShowInput> {
    return await to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    thumbnailUrl?: string;
    showId: ShowId;
    description: string;
    seasonId: SeasonId;
    episodeNumber: bigint;
    durationSeconds: bigint;
    videoUrl?: string;
}): {
    title: string;
    thumbnailUrl: [] | [string];
    showId: _ShowId;
    description: string;
    seasonId: _SeasonId;
    episodeNumber: bigint;
    durationSeconds: bigint;
    videoUrl: [] | [string];
} {
    return {
        title: value.title,
        thumbnailUrl: value.thumbnailUrl ? candid_some(value.thumbnailUrl) : candid_none(),
        showId: value.showId,
        description: value.description,
        seasonId: value.seasonId,
        episodeNumber: value.episodeNumber,
        durationSeconds: value.durationSeconds,
        videoUrl: value.videoUrl ? candid_some(value.videoUrl) : candid_none()
    };
}
async function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coverImageUrl?: string;
    title: string;
    trailerBlob?: ExternalBlob;
    description: string;
    isFree: boolean;
    category: Category;
}): Promise<{
    coverImageUrl: [] | [string];
    title: string;
    trailerBlob: [] | [_ExternalBlob];
    description: string;
    isFree: boolean;
    category: _Category;
}> {
    return {
        coverImageUrl: value.coverImageUrl ? candid_some(value.coverImageUrl) : candid_none(),
        title: value.title,
        trailerBlob: value.trailerBlob ? candid_some(await to_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.trailerBlob)) : candid_none(),
        description: value.description,
        isFree: value.isFree,
        category: to_candid_Category_n30(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    profilePicBlob?: ExternalBlob;
}): Promise<{
    bio: string;
    username: string;
    profilePicBlob: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio,
        username: value.username,
        profilePicBlob: value.profilePicBlob ? candid_some(await to_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.profilePicBlob)) : candid_none()
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title?: string;
    thumbnailUrl?: string;
    description?: string;
    episodeNumber?: bigint;
    durationSeconds?: bigint;
    videoUrl?: string;
}): {
    title: [] | [string];
    thumbnailUrl: [] | [string];
    description: [] | [string];
    episodeNumber: [] | [bigint];
    durationSeconds: [] | [bigint];
    videoUrl: [] | [string];
} {
    return {
        title: value.title ? candid_some(value.title) : candid_none(),
        thumbnailUrl: value.thumbnailUrl ? candid_some(value.thumbnailUrl) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        episodeNumber: value.episodeNumber ? candid_some(value.episodeNumber) : candid_none(),
        durationSeconds: value.durationSeconds ? candid_some(value.durationSeconds) : candid_none(),
        videoUrl: value.videoUrl ? candid_some(value.videoUrl) : candid_none()
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title?: string;
    seasonNumber?: bigint;
}): {
    title: [] | [string];
    seasonNumber: [] | [bigint];
} {
    return {
        title: value.title ? candid_some(value.title) : candid_none(),
        seasonNumber: value.seasonNumber ? candid_some(value.seasonNumber) : candid_none()
    };
}
async function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ShowId;
    coverImageUrl?: string;
    title: string;
    trailerBlob?: ExternalBlob;
    description: string;
    isFree: boolean;
    category: Category;
}): Promise<{
    id: _ShowId;
    coverImageUrl: [] | [string];
    title: string;
    trailerBlob: [] | [_ExternalBlob];
    description: string;
    isFree: boolean;
    category: _Category;
}> {
    return {
        id: value.id,
        coverImageUrl: value.coverImageUrl ? candid_some(value.coverImageUrl) : candid_none(),
        title: value.title,
        trailerBlob: value.trailerBlob ? candid_some(await to_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.trailerBlob)) : candid_none(),
        description: value.description,
        isFree: value.isFree,
        category: to_candid_Category_n30(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Drama: null;
} | {
    Exclusive: null;
} | {
    RealityTV: null;
} | {
    Comedy: null;
} {
    return value == Category.Drama ? {
        Drama: null
    } : value == Category.Exclusive ? {
        Exclusive: null
    } : value == Category.RealityTV ? {
        RealityTV: null
    } : value == Category.Comedy ? {
        Comedy: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    Pro: null;
} | {
    Premium: null;
} | {
    Free: null;
} {
    return value == SubscriptionTier.Pro ? {
        Pro: null
    } : value == SubscriptionTier.Premium ? {
        Premium: null
    } : value == SubscriptionTier.Free ? {
        Free: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
